name:                vessel
version:             0.1.0.0

dependencies:
- base

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  vessel-runner:
    main:                Main.hs
    source-dirs:         app
    c-sources:
      c-source/fastvector.c
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - base16-bytestring
      - binary
      - bytestring
      - bytestring-trie
      - containers
      - deepseq
      - half
      - split
      - vector
